### ISSUE TITLE
setJoints issues

### ISSUE THREAD

**Issue by David78444** [henriksod/Fabrik2DArduino#12]
The setJoints method seems to have a couple issues.

When I first tried the method, it had no effect. When I looked at the source I saw:
    int angListLen = sizeof(angles)/sizeof(float);
    int lenListLen = sizeof(lengths)/sizeof(float);
    if (angListLen == numJoints && lenListLen == numJoints-1) 

I think this if statement is never true. The lengths are ints, so I changed sizeof(float) to sizeof(int) for the lengths, and tried different lengths of arrays for lengths and angles, but still nothing, so I got rid of the if statement.

After that, the results were incorrect, so I made a modification.

Original:
       float accAng = angles[0];
       for (int i = 1; i < this->numJoints; i++)
       {
           accAng += angles[i];

Modified:
       float accAng = 0;
       for (int i = 1; i < this->numJoints; i++)
       {
           accAng += angles[i-1];

These modifications work for my case of 2 links, 3 joints.

**Comment by henriksod** [comment]
Thank you for this finding, David. I haven't had time to fully test this function. I will look into this based on your modification.
