### ISSUE TITLE
What tool did you used to make the example GIF ?

### ISSUE THREAD

**Issue by sucrecacao** [henriksod/Fabrik2DArduino#14]
Hi ! 

I would like to create a small simulator for my arm robot so I was wondering which tool did you used to create the animated gif ?

**Comment by henriksod** [comment]
Hi, I used Processing.

**Comment by sucrecacao** [comment]
Is the code available somewhere ?

**Comment by henriksod** [comment]
Yes, the processing files are in the examples idrectory in this repo. As .pde files.
