### ISSUE TITLE
Example "3DOFToolAngle" is the same as "3DOFMoveCircle"

### ISSUE THREAD

**Issue by robonxt** [henriksod/Fabrik2DArduino#17]
Is it just me, or is the example "3DOFToolAngle" the same as "3DOFMoveCircle"?

**Comment by henriksod** [comment]
Hi, 3DOFMoveCircle does not make use of Tool Angle. The Tool Angle is used if you want the manipulator to approach the target from a desired angle.

**Comment by robonxt** [comment]
Huh, probably just my eyes playing tricks on me.  Anyways, thank you for making this library!
