### ISSUE TITLE
Board hangs when running example_3DOFToolAngle

### ISSUE THREAD

**Issue by xchg-dot-ca** [henriksod/Fabrik2DArduino#19]
Weird issue, but Adafruit Trinked M0 ( Atmel ATSAMD21 based board )
Hangs when running example_3DOFToolAngle sketch, unmodified!
I cannot wrap my mind why this is happening, but this clearly related to the fact that I has to solve the IK when tool has to be at the certain angle.
Do you have any ideas how can I debug this?
Thank you.

**Comment by xchg-dot-ca** [comment]
Tested on Adafruit ItsiBitsy nFR52840 - same issue, it hangs pretty much the same way!

**Comment by henriksod** [comment]
Hi, does it hang when it is in the solve function or outside? Try to do some prints to Serial at different locations

**Comment by xchg-dot-ca** [comment]
Thank you for the reply, 
It seems to me as this is stack(memory?) corruption or something to this extend

As it enters all function calculates the solution, 
`returns from bool solvable = solve(oc_x, oc_y, lengths);`
continues to the very end of 
`bool Fabrik2D::solve2(float x, float y, float z, float toolAngle, float grippingOffset, int* lengths)`
and after that never comes back to the main loop! and just hangs

**Comment by xchg-dot-ca** [comment]
Oh wow, I think I have found a bug !
Funciton: 

bool Fabrik2D::solve2(float x, float y, float z, float toolAngle, float grippingOffset, int* lengths)

Missing a return statement, and I guess some implementations are getting confused....
I will post a PR

**Comment by xchg-dot-ca** [comment]
Wondering if I can set somewhere -Wreturn-type or -Wall in Arduino IDE to prevent such thin from compiling !

**Comment by xchg-dot-ca** [comment]
Issue resolved, fix commited

**Comment by robonxt** [comment]
Interesting, on ESP8266 and ESP32 boards, the latest (v1.0.3) library still crashes the board (gives off errors and resets the ESPs). I fixed it by adding ```return solvable;``` to the end of the function 
```bool Fabrik2D::solve2(float x, float y, float z, float toolAngle, float grippingOffset, int* lengths)``` in ```FABRIK2D.cpp```

**Comment by henriksod** [comment]
Hi, I guess we need to create a new tag based on master to get the fix into arduino libraries
