### ISSUE TITLE
negative angles when working with negative coordinates

### ISSUE THREAD

**Issue by JARVIS843** [henriksod/Fabrik2DArduino#25]
Developed a model that works perfectly for positive coordinates, but does the library support negative coordinates as input?

**Comment by henriksod** [comment]
Hi! Yes it should. It all depends on the angles being calculated and if they are valid for the chain of links that you have set up.

**Comment by JARVIS843** [comment]
When inputting a negative coordinate, is the IK result a mirror of its positive-coordinate counterpart?

**Comment by henriksod** [comment]
hi, no, it will be a solution that is closest to its previous solution. For example, let's say that your robot is standing on a table. Then the table can be considered the ground plane where y=0. If you want to reach under the table, then you would have to specify a negative y coordinate. Now imagine how the robot would then reach below the table. It is no different than reaching downwards from an arbitrary positive position to another positive position.

If you mean that you want the robot to reach backward, then it depends on if you have a rotating base or not. With a rotating base, this library first attempts to rotate so it is aligned with the point you want to reach, then solves the IK. 

If you do not have a rotating base, it should attempt to bend backward creating a somewhat "mirrored" configuration.

**Comment by JARVIS843** [comment]
Thanks for the help. Issue Closed
