### ISSUE TITLE
How to limit the angles of the joints?

### ISSUE THREAD

**Issue by undermuz** [henriksod/Fabrik2DArduino#3]
So that the algorithm solves angles from -90 to 90 for each joint and base?

**Comment by henriksod** [comment]
For the moment, you have to specify this yourself before you write the computed angle to the servos, like the following:
`shoulder.write(min(180, max(0, shoulderAngle + 180/2)));`

This will limit the output to the servo between -90 and 90 degrees, remember that the servo is at its center position at 90 degrees.

I could add options to limit joints in the library itself, but I think this will interfere with the conventional interface I use as of now. Is this solution sufficient for you or do you want to see such a feature implemented into the library instead? This could potentially make the interface overcomplicated.

**Comment by undermuz** [comment]
@henriksod When I use this code, I see wrong position of servos on the emulator

Without angle conversion:
Emulator video: [link1](https://tinytake.s3.amazonaws.com/pulse/undermuz/attachments/9868200/TinyTake09-02-2019-03-01-54.mp4)

Code:
![image](https://user-images.githubusercontent.com/6875507/52520664-e9b48700-2c7c-11e9-9273-bd148b9ce580.png)

With angle conversion
Emulator video: [link2](https://tinytake.s3.amazonaws.com/pulse/undermuz/attachments/9868213/TinyTake09-02-2019-03-05-42.mp4)

Code:
![image](https://user-images.githubusercontent.com/6875507/52520670-fcc75700-2c7c-11e9-931b-f1f6a8acd3ff.png)

Tell me what I'm doing wrong please

**Comment by henriksod** [comment]
I see. This is obviously a mistake on my part. Have you tried setting a tool angle also? Are the angles correct then? There is an example in the examples folder.

**Comment by henriksod** [comment]
I have done some testing and I do not know why you get those results. According to my tests, the computed angles are correct.

This is the test I run (I do not have any arduino at hand at the moment, so I wrote a small C++ program):
```c++
//============================================================================
// Test regarding issue #3
//
// Name        : KinematicsTest.cpp
// Author      : Henrik Söderlund
//============================================================================

#include <iostream>
#include <string>
#include <cmath>

#include "FABRIK2D.h"

using namespace std;

// A function to validate IK of a 2DOF robotic arm. True means it is correct,
// false means it is incorrect.
bool validateIK (float* angles, float x, float y, int* lengths);

int main()
{

	// Based on issue #3
	float deg1 = 0;

	// Initialize Fabrik2D, based on 2DOF example
	int lengths[] = {225, 150};
	Fabrik2D fabrik2D(3, lengths);
	fabrik2D.setTolerance(0.5);

	// Iterate 10 times
	for (int i = 0; i < 10; i++)
	{

		// Increase deg1 by 10 degrees each iteration
		deg1 = deg1 + 10;

		if (deg1 > 360) {
			deg1 = 0;
		}

		// Convert to radians
		float rad1 = deg1 * M_PI / 180;

		// Update desired x,y, moving in a circle with radius 30 with center at (100,100)
		float des_x = 100 + 30*cos(rad1);
		float des_y = 100 + 30*sin(rad1);

		// Print desired position
		cout << "Desired end effector pos:\t" << to_string(des_x) << "\t" << to_string(des_y) << endl;

		// Solve IK
		fabrik2D.solve(des_x,des_y,lengths);

		// Get solved joint angles (in radians!)
		float jointAngle_1 = fabrik2D.getAngle(0);
		float jointAngle_2 = fabrik2D.getAngle(1);

		// Get solved x,y
		float x = fabrik2D.getX(2);
		float y = fabrik2D.getY(2);
		// Print computed position
		cout << "Computed end effector pos:\t" << to_string(x) << "\t" << to_string(y) << endl;

		// Validate computed pos on true pos
		float angles[] = {jointAngle_1,jointAngle_2};
		bool valid = validateIK(angles, x, y, lengths);

		// Print joint angles in degrees
		cout << "Joint angles:\t\t\t" << to_string(jointAngle_1* 57296 / 1000) << "\t" << to_string(jointAngle_2* 57296 / 1000) << endl;

		// Print validation result
		cout << "Computation valid:\t\t" << to_string(valid) << endl;

	}

	return 0;
}

// A function to validate IK of a 2DOF robotic arm. True means it is correct,
// false means it is incorrect. Performs forward kinematics.
bool validateIK (float* angles, float x, float y, int* lengths)
{

	// Check how many joints, length array has to be the same size or crash (optimal programming)!
	int angListLen = sizeof(angles)/sizeof(float);

	// We use a variable to store the sum of angles each iteration
	float angSum = 0;

	// Initialize pos variables
	float true_x = 0;
	float true_y = 0;

	// Iterate for each joint angle
	for (int i = 0; i < angListLen; i++)
	{
		// Add angle to sum
		angSum += angles[i];

		// Update true x and y
		true_x += lengths[i]*cos(angSum);
		true_y += lengths[i]*sin(angSum);
	}

	// Print true position
	cout << "True end effector pos:\t\t" << to_string(true_x) << "\t" << to_string(true_y) << endl;

	// Check if it is a match
	if (round(x) == round(true_x) && round(y) == round(true_y))
	{
		return true;
	}

	return false;

}
```


This is the output of the program:

> Desired end effector pos:	129.544235	105.209442
> Computed end effector pos:	129.281250	105.535225
> True end effector pos:		129.281250	105.535225
> Joint angles:			81.035408	-132.123245
> Computation valid:		1
> Desired end effector pos:	128.190781	110.260605
> Computed end effector pos:	128.432846	109.983131
> True end effector pos:		128.432831	109.983116
> Joint angles:			82.383476	-131.281982
> Computation valid:		1
> Desired end effector pos:	125.980759	115.000000
> Computed end effector pos:	126.274872	114.688301
> True end effector pos:		126.274895	114.688324
> Joint angles:			84.048447	-130.711243
> Computation valid:		1
> Desired end effector pos:	122.981339	119.283630
> Computed end effector pos:	123.287842	118.980888
> True end effector pos:		123.287827	118.980896
> Joint angles:			85.777466	-130.423431
> Computation valid:		1
> Desired end effector pos:	119.283630	122.981339
> Computed end effector pos:	119.602676	122.684883
> True end effector pos:		119.602684	122.684914
> Joint angles:			87.524780	-130.423370
> Computation valid:		1
> Desired end effector pos:	115.000000	125.980759
> Computed end effector pos:	115.335320	125.684601
> True end effector pos:		115.335320	125.684608
> Joint angles:			89.260124	-130.711151
> Computation valid:		1
> Desired end effector pos:	110.260605	128.190781
> Computed end effector pos:	110.615387	127.889580
> True end effector pos:		110.615387	127.889595
> Joint angles:			90.951027	-131.281738
> Computation valid:		1
> Desired end effector pos:	105.209450	129.544235
> Computed end effector pos:	105.584785	129.234131
> True end effector pos:		105.584793	129.234131
> Joint angles:			92.560944	-132.125214
> Computation valid:		1
> Desired end effector pos:	100.000000	130.000000
> Computed end effector pos:	100.184845	129.849884
> True end effector pos:		100.184837	129.849869
> Joint angles:			94.142990	-133.223907
> Computation valid:		1
> Desired end effector pos:	94.790558	129.544235
> Computed end effector pos:	95.165565	129.238571
> True end effector pos:		95.165550	129.238586
> Joint angles:			95.382523	-134.565460
> Computation valid:		1

Anyhow, I will implement some sort of constraint feature in the future for the inverse kinematics. They actually propose an algorithm in the paper which could be implemented. We will see when I get time to do this though...

**Comment by undermuz** [comment]
@henriksod Your library returns correct angles, but your example code to limit [-90,90]:
`shoulder.write(min(180, max(0, shoulderAngle + 180/2)));`
returns incorrect angle values

I will try toolAngle like you asked above in a few days and share with you the results.

**Comment by undermuz** [comment]
@henriksod 
https://undermuz.tinytake.com/sf/MzMzNjk5OV85OTg0ODI4

with set tool angle -90

I thought that if the absolute value of the angles is not more than 180, then I will be able to configure my servos without limit in the code

**Comment by henriksod** [comment]
The angles look correct in your animation. I will implement the angle constraints more properly in a future release.
