### ISSUE TITLE
how to find tool angel?

### ISSUE THREAD

**Issue by yurasakun** [henriksod/Fabrik2DArduino#8]
i use your library for my arm, but I don't understand what is meant by tool angle. Please help me

**Comment by henriksod** [comment]
The tool angle is the angle in which the tool approaches the object. If you set the tool angle to -90 degrees, then the arm will approach the object from above. If you set it to 0 degrees, it will approach the object from the side. Is this sufficient for an explanation?

**Comment by yurasakun** [comment]
Thanks, i understand! I use the MPu6050 to control my hand, and I transfer Bluetooth data, so  is it necessary to transform  x y z to other values ​​for your library?

**Comment by henriksod** [comment]
That depends on the reference coordinate system. I do not know how you have positioned your IMU, but if you take a look at how the axes are oriented on the module and compare that to the configuration examples where I have drawn the coordinate systems, you should get a general idea of what transformation you will have to do from [x,y,z]_IMU to [x,y,z]_ARM. Good luck!

**Comment by yurasakun** [comment]
i don't understand how trasform [x,y,z]_IMU to [x,y,z]_ARM. I know what in IMU  start point x=2, y = 0, z = 11, and if my arm is tilted down and stretched forward, x y z on picture 
![Записати](https://user-images.githubusercontent.com/30806775/59623027-cbcfc500-913b-11e9-9835-85db629dca5c.PNG)
