### ISSUE TITLE
how transform [x,y,z]_IMU to [x,y,z]_ARM.

### ISSUE THREAD

**Issue by yurasakun** [henriksod/Fabrik2DArduino#9]
i don't understand how trasform [x,y,z]_IMU to [x,y,z]_ARM. I know what in IMU start point x=2, y = 0, z = 11, and if my arm is tilted down and stretched forward, x y z on picture
![Записати](https://user-images.githubusercontent.com/30806775/59623321-8fe92f80-913c-11e9-9620-17b1300855db.PNG)
Help please

**Comment by henriksod** [comment]
I do not fully understand your question. Qould you maybe draw the coordinate system of the IMU relative to the robotic arm? Or are the axes of the IMU aligned with the robotic arm and it is merely a question of offset?

Take care

**Comment by yurasakun** [comment]
Hi, I understand how transform [x,y,z]_IMU to [x,y,z]_ARM. But I have one question abaut tool angel. 
it does not coincide with the concept "pitch roll yaw" or rather with "pitch"

**Comment by henriksod** [comment]
The tool angle is a rotation along the z-axis that determines the angle in which the robotic arm end effector approaches the object of interest at location (x_e, y_e, z_e). Depending on how you place the IMU on your hand, it feels natural to determine the tool angle based on the tilt of the wrist. Since I do not know how you orient the IMU on your hand, I cannot say which axis on the IMU that corresponds to the z-axis of the robotic arm.

**Comment by yurasakun** [comment]
I send  video in the evening

**Comment by yurasakun** [comment]
hello, sorry what don't video
I'm drow picture 
![Без імені](https://user-images.githubusercontent.com/30806775/59962602-54f64b80-94f0-11e9-836d-7e80bbd808cc.png)
Please help I'm now use toolAngel = - M_Pi
My cod for transform [x,y,z]_IMU to [x,y,z]_ARM:
`float rad1 = (x*600) * M_PI / 180;
    float rad2 = (y*500) * M_PI / 180;
float des_x = 100 - rad1;
float des_y = 100 + rad2;
fabrik2D.solve2(des_x,des_y,  z,-M_PI/2.5,0, lengths);
`

**Comment by yurasakun** [comment]
I don't understand how transform imu_z to arm_z

**Comment by yurasakun** [comment]
And yet I have not been able to convert [x,y,z]_IMU to [x,y,z]_ARM
in my imu sensor x,y,z =[-10,10]

**Comment by henriksod** [comment]
You should use the accelerometer on the IMU to get the translational movement. I do not understand why you are sending angles into solve function... x y and z are in millimeters. Look online how you can get the position of the IMU from the accelerometer data. This will grant you x y and z of the IMU and can be translated to the arm after that. As for the tool angle, you would want to sensor fuse the Gyroscope with the Accelerometer (Complementary Filter is enough) to get the rotation along the z-axis and then apply that to the arm tool angle.

**Comment by yurasakun** [comment]
I found 
` t = millis();
  Vector normAccel = mpu.readNormalizeAccel();
  
  x = normAccel.XAxis;
  y = normAccel.YAxis;
  z = normAccel.ZAxis;
  
  int roll = (atan2(normAccel.YAxis, normAccel.ZAxis)*180.0)/M_PI;
  delay(10);
  

  speedX = speedX + x * dt;
  
  posX = posX + speedX * dt;
  
  speedY = speedY + y * dt;
  
  posY = posY + speedY * dt;
  
  speedZ = speedZ + z * dt;
  
  posZ = posZ + speedZ * dt;
  dt = millis() - t;`
but 
![Записати](https://user-images.githubusercontent.com/30806775/59975050-6016ad80-95bc-11e9-9bc2-189cbe9d4a69.PNG)

**Comment by henriksod** [comment]
This looks reasonable to me. Make sure to calibrate the accelerometer before using it. There should be procedures online. To remove the large offset, place the accelerometer on a flat surface, run the program and use these offsets and subtract them from the output of the accelerometer.

**Comment by yurasakun** [comment]
Thanks!
